/** Map nationality / country strings to ISO 3166-1 alpha-2 for flags */

const ISO2 = /^[a-z]{2}$/i;

const DEMONYM_AND_COUNTRY: Record<string, string> = {
  american: "US",
  usa: "US",
  "united states": "US",
  "u.s.": "US",
  us: "US",
  british: "GB",
  english: "GB",
  scottish: "GB",
  welsh: "GB",
  "united kingdom": "GB",
  uk: "GB",
  irish: "IE",
  ireland: "IE",
  canadian: "CA",
  canada: "CA",
  mexican: "MX",
  mexico: "MX",
  brazilian: "BR",
  brazil: "BR",
  russian: "RU",
  russia: "RU",
  ukrainian: "UA",
  ukraine: "UA",
  polish: "PL",
  poland: "PL",
  german: "DE",
  germany: "DE",
  french: "FR",
  france: "FR",
  italian: "IT",
  italy: "IT",
  spanish: "ES",
  spain: "ES",
  portuguese: "PT",
  portugal: "PT",
  dutch: "NL",
  netherlands: "NL",
  belgian: "BE",
  belgium: "BE",
  swedish: "SE",
  sweden: "SE",
  norwegian: "NO",
  norway: "NO",
  danish: "DK",
  denmark: "DK",
  finnish: "FI",
  finland: "FI",
  icelandic: "IS",
  iceland: "IS",
  australian: "AU",
  australia: "AU",
  "new zealander": "NZ",
  "new zealand": "NZ",
  japanese: "JP",
  japan: "JP",
  chinese: "CN",
  china: "CN",
  "south korean": "KR",
  "south korea": "KR",
  korean: "KR",
  korea: "KR",
  thai: "TH",
  thailand: "TH",
  filipino: "PH",
  philippines: "PH",
  indonesian: "ID",
  indonesia: "ID",
  indian: "IN",
  india: "IN",
  pakistani: "PK",
  pakistan: "PK",
  israeli: "IL",
  israel: "IL",
  turkish: "TR",
  turkey: "TR",
  georgian: "GE",
  georgia: "GE",
  armenian: "AM",
  armenia: "AM",
  azerbaijani: "AZ",
  azerbaijan: "AZ",
  kazakh: "KZ",
  kazakhstan: "KZ",
  uzbek: "UZ",
  uzbekistan: "UZ",
  cuban: "CU",
  cuba: "CU",
  jamaican: "JM",
  jamaica: "JM",
  "puerto rican": "PR",
  "puerto rico": "PR",
  colombian: "CO",
  colombia: "CO",
  venezuelan: "VE",
  venezuela: "VE",
  argentine: "AR",
  argentinian: "AR",
  argentina: "AR",
  chilean: "CL",
  chile: "CL",
  peruvian: "PE",
  peru: "PE",
  ecuadorian: "EC",
  ecuador: "EC",
  nigerian: "NG",
  nigeria: "NG",
  "south african": "ZA",
  "south africa": "ZA",
  egyptian: "EG",
  egypt: "EG",
  moroccan: "MA",
  morocco: "MA",
  algerian: "DZ",
  algeria: "DZ",
  tunisian: "TN",
  tunisia: "TN",
  cameroonian: "CM",
  cameroon: "CM",
  ghanaian: "GH",
  ghana: "GH",
  kenyan: "KE",
  kenya: "KE",
  swiss: "CH",
  switzerland: "CH",
  austrian: "AT",
  austria: "AT",
  hungarian: "HU",
  hungary: "HU",
  romanian: "RO",
  romania: "RO",
  bulgarian: "BG",
  bulgaria: "BG",
  serbian: "RS",
  serbia: "RS",
  croatian: "HR",
  croatia: "HR",
  bosnian: "BA",
  "bosnia and herzegovina": "BA",
  slovenian: "SI",
  slovenia: "SI",
  slovak: "SK",
  slovakia: "SK",
  czech: "CZ",
  "czech republic": "CZ",
  czechia: "CZ",
  lithuanian: "LT",
  lithuania: "LT",
  latvian: "LV",
  latvia: "LV",
  estonian: "EE",
  estonia: "EE",
  belarusian: "BY",
  belarus: "BY",
  moldovan: "MD",
  moldova: "MD",
  greek: "GR",
  greece: "GR",
  cypriot: "CY",
  cyprus: "CY",
  iraqi: "IQ",
  iraq: "IQ",
  iranian: "IR",
  iran: "IR",
  saudi: "SA",
  "saudi arabian": "SA",
  "saudi arabia": "SA",
  emirati: "AE",
  "united arab emirates": "AE",
  uae: "AE",
  qatari: "QA",
  qatar: "QA",
  kuwaiti: "KW",
  kuwait: "KW",
  lebanese: "LB",
  lebanon: "LB",
  jordanian: "JO",
  jordan: "JO",
  syrian: "SY",
  syria: "SY",
  afghan: "AF",
  afghanistan: "AF",
  nepalese: "NP",
  nepal: "NP",
  bangladeshi: "BD",
  bangladesh: "BD",
  "sri lankan": "LK",
  "sri lanka": "LK",
  singaporean: "SG",
  singapore: "SG",
  malaysian: "MY",
  malaysia: "MY",
  vietnamese: "VN",
  vietnam: "VN",
  cambodian: "KH",
  cambodia: "KH",
  laotian: "LA",
  laos: "LA",
  mongolian: "MN",
  mongolia: "MN",
  taiwanese: "TW",
  taiwan: "TW",
  "hong kong": "HK",
  macanese: "MO",
  macau: "MO",
  "republic of ireland": "IE",
  "northern irish": "GB",
  "costa rican": "CR",
  "costa rica": "CR",
  panamanian: "PA",
  panama: "PA",
  honduran: "HN",
  honduras: "HN",
  guatemalan: "GT",
  guatemala: "GT",
  salvadoran: "SV",
  "el salvador": "SV",
  nicaraguan: "NI",
  nicaragua: "NI",
  uruguayan: "UY",
  uruguay: "UY",
  paraguayan: "PY",
  paraguay: "PY",
  bolivian: "BO",
  bolivia: "BO",
  surinamese: "SR",
  suriname: "SR",
  trinidadian: "TT",
  trinidad: "TT",
  bahamian: "BS",
  bahamas: "BS",
  barbadian: "BB",
  barbados: "BB",
  dominican: "DO",
  "dominican republic": "DO",
  haitian: "HT",
  haiti: "HT",
  senegalese: "SN",
  senegal: "SN",
  ivorian: "CI",
  "ivory coast": "CI",
  "côte d'ivoire": "CI",
  congolese: "CD",
  "democratic republic of the congo": "CD",
  ethiopian: "ET",
  ethiopia: "ET",
  tanzanian: "TZ",
  tanzania: "TZ",
  ugandan: "UG",
  uganda: "UG",
  zimbabwean: "ZW",
  zimbabwe: "ZW",
  zambian: "ZM",
  zambia: "ZM",
  namibian: "NA",
  namibia: "NA",
  botswanan: "BW",
  botswana: "BW",
  mozambican: "MZ",
  mozambique: "MZ",
  angolan: "AO",
  angola: "AO",
  libyan: "LY",
  libya: "LY",
  sudanese: "SD",
  sudan: "SD",
  somali: "SO",
  somalia: "SO",
  yemeni: "YE",
  yemen: "YE",
  omani: "OM",
  oman: "OM",
  bahraini: "BH",
  bahrain: "BH",
  palestinian: "PS",
  palestine: "PS",
};

export function nationalityToCountryCode(nationality?: string | null): string | null {
  if (!nationality?.trim()) return null;
  const raw = nationality.trim();
  const key = raw.toLowerCase();
  if (key === "international" || key === "global" || key === "—" || key === "-")
    return null;
  if (ISO2.test(raw)) return raw.toUpperCase();
  if (DEMONYM_AND_COUNTRY[key]) return DEMONYM_AND_COUNTRY[key];
  for (const [name, code] of Object.entries(DEMONYM_AND_COUNTRY)) {
    if (key.includes(name) || name.includes(key)) return code;
  }
  return null;
}

/** Regional indicator symbols — works without external images */
export function countryCodeToFlagEmoji(code: string): string {
  const c = code.toUpperCase();
  if (!ISO2.test(c)) return "🌐";
  return String.fromCodePoint(
    ...[...c].map((ch) => 0x1f1e6 + ch.charCodeAt(0) - 65)
  );
}

export function flagImageUrl(code: string, width = 40): string {
  return `https://flagcdn.com/w${width}/${code.toLowerCase()}.png`;
}
